### ISSUE TITLE
How to use only syntax color/highlighting?

### ISSUE THREAD

**Issue by ahizap** [eenaree/webstorm-new-ui-theme#13]
The syntax highlighting of this extension is really great and I want use this with other themes. So, I tried copying the content of `new_dark.json` from `semanticHighlighting: true` to the end of the file into `editor.tokenColorCustomizations{}` basically skipping `colors` but it didn't work. Any help regarding this is much appreciated.

**Comment by eenaree** [comment]
@ahizap You can refer to this link.

`semanticTokenColors` is https://code.visualstudio.com/docs/getstarted/themes#_editor-semantic-highlighting
`tokenColors` is https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting

Maybe, like this?

![스크린샷 2024-07-30 175648](https://github.com/user-attachments/assets/780078d6-e1fd-4421-8508-52c56a65d39d)
