### ISSUE TITLE
Selected text not visible when word highlight is also active

### ISSUE THREAD

**Issue by SanjoSolutions** [eenaree/webstorm-new-ui-theme#8]
When I had selected a part of a word, the selected part was no longer visible because the whole word was highlighted with the word highlight color. Adding some transparency to the word highlight color seems to fix this.

I have added the following to the settings.json as a fix:

```json
{
  // ...
  "workbench.colorCustomizations": {
    "editor.wordHighlightBackground": "#ecebfb7c",
    "editor.wordHighlightStrongBackground": "#fce8f47c"
  }
}
```

**Comment by eenaree** [comment]
I apologize for seeing the issue so late.
I was aware of it, but didn't realize that I should have given it transparency.

`The color must not be opaque so as not to hide underlying decorations.` I overlooked that.

So I'm trying to give it transparency value like this.

```json
"editor.wordHighlightBackground": "#ccccff66",
"editor.wordHighlightStrongBackground": "#ffcdff66"
```

Giving transparency to the existing color was too opaque, so i made it transparent on a darker color.

And when `selectionHighlightBackground` and `wordHighlightBackground` overlap, the color of `selectionHighlightBackground` is not clear, so i want to give it transparency in a darker color as well.

```json
"editor.selectionHighlightBackground": "#aadfa980"
```

I was wondering what your thoughts are on this.

**Comment by eenaree** [comment]
Additionally, there are a few settings in workbench.colorCustomizations that require transparency.

Because they are opaque, `wordHighlightBackground` and `selectionHighlightBackground` are not visible when overlapped.
